#!/bin/bash
# source ./.env

LATEST_CDX_VERSION=$(curl -sSL https://api.github.com/repos/cyclonedx/cyclonedx-cli/releases/latest \
                   | grep '"name":' \
                   | head -1 \
                   | cut -d : -f 2,3 \
                   | tr -d '[:space:]\",')

PLUGIN_HOME="${HOME}/.trivy/plugins/${GIT_REPO}"
echo ${GOOS} ${GOARCH}

if [ ! -f ${PLUGIN_HOME}/cdx-cli ]
then
    echo "${PLUGIN_HOME}/cdx-cli does not exist in Bash"
    curl -o ${PLUGIN_HOME}/cdx-cli ${LATEST_CDX_VERSION}
    chmod +x curl -o ${PLUGIN_HOME}/cdx-cli
# else
#     echo "File found. Do something meaningful here"
fi



# Usage
function usage() {
  cat << EOS >&2
Usage: trivy ${GIT_REPO} [-h,--help] TYPE NAME [TRIVY OPTION]
 A Trivy plugin that scans the images of a kubernetes resource.

Options:
  -h, --help    Show usage.

Examples:
  # Scan a Pod
  trivy ${GIT_REPO} pod mypod

  # Scan a Deployment
  trivy ${GIT_REPO} deployment mydeployment -n mynamespace

  # Scan a Job and filter by severity
  trivy ${GIT_REPO} job myjob -n mynamespace -- --severity CRITICAL
EOS
  exit
}


function scan {
  trivy image $@
}


if [[ ($# -eq 0) || ($1 == "--help") || ($1 == "-h") ]]; then
  # No commands or the --help flag passed and we'll show the usage instructions
  usage
fi

REPO_PARAM=()
for opt in "$@"; do
  case "${opt}" in
    '--' )
      shift
      TRIVY_PARAM=( "$@" )
      break
      ;;
    * )
      if [ -n "$1" ]; then
        KUBECTL_PARAM+=("$1")
      fi
      shift
      ;;
  esac
done


images=$(kubectl get "${REPO_PARAM[@]}" -oyaml | sed -nE 's@[^\w]*image: ([a-zA-Z0-9/:])@\1@p' | uniq)
while read -r image; do
  if [ -n "$image" ]; then
    scan "${TRIVY_PARAM[@]}" "$image"
  fi
done <<< "$images"

