name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Replace
        run: source .env; envsubst < plugin.yaml.tmp > plugin.yaml
      - name: Compress
        run: tar -zcvf trivy-bomtools.tar.gz trivy-bomtools LICENSE .env
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            trivy-bomtools.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
