name: Release

on:
  push:
    tags:
      - "v*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Capture Version
        run: |
          echo $(curl -sSL https://api.github.com/repos/${GITHUB_ORG_USR}/${GITHUB_REPO}/releases/latest \
                   | grep '"name":' \
                   | head -1 \
                   | cut -d : -f 2,3 \
                   | tr -d '[:space:]\",')
      - name: Replace
        run: source .env; envsubst < plugin.yaml.tmp > plugin.yaml
      - name: Compress
        run: tar -zcvf trivy-bomtools.tar.gz trivy-bomtools LICENSE .env
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            trivy-bomtools.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
